on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
    
    - run: ls -la && pwd

    - name: Test Local Action
      id: test-action
      uses: ./
      with:
        milliseconds: 1000

    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"